name: Build & Upload APK to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.1"

      - name: Install dependencies
        run: npm ci

      - name: Build web (if needed)
        run: npm run build

      - name: Capacitor sync android
        run: npx cap sync android

      - name: Capacitor copy android
        run: npx cap copy android

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Find APK path
        id: apk
        run: |
          APK_PATH=$(find $GITHUB_WORKSPACE/android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
